// Seed data — source of truth for sovereignty_db_free. D1 is derived from this file.
// All updates must come via PR to this file, never via direct SQL UPDATE (decision #6).
// Seed is idempotent: INSERT ... ON CONFLICT DO UPDATE.
//
// Sources:
//   Stripe Projects providers: verified against projects.dev/providers/ (addendum §5.1)
//   Anthropic records: 3 separate entries per addendum §5.2, verified via official-docs

import type { ProviderRow } from "@/types";

type SeedRow = Omit<ProviderRow, "created_at" | "updated_at">;

export const PROVIDERS: SeedRow[] = [
  // -------------------------------------------------------------------------
  // Stripe Projects providers (32) — verified against projects.dev/providers/
  // -------------------------------------------------------------------------
  {
    id: "agentmail",
    name: "AgentMail",
    category: "Communications",
    description: "Email API for AI agents",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "algolia",
    name: "Algolia",
    category: "Search",
    description: "Search and discovery API",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available; US-parent remains CLOUD Act subject",
  },
  {
    id: "amplitude",
    name: "Amplitude",
    category: "Analytics",
    description: "Product analytics platform",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU data residency available on enterprise plans",
  },
  {
    id: "auth0",
    name: "Auth0/Okta",
    category: "Auth",
    description: "Identity and authentication platform",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU deployment available; Okta US parent subject to CLOUD Act",
  },
  {
    id: "browserbase",
    name: "Browserbase",
    category: "Sandbox",
    description: "Cloud browser infrastructure for AI agents",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "chroma",
    name: "Chroma",
    category: "Database",
    description: "Open-source vector database",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "Self-hosted deployment achieves EU residency; cloud service is US-only",
  },
  {
    id: "clerk",
    name: "Clerk",
    category: "Auth",
    description: "User authentication and management for developers",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU data residency available; US-incorporated parent subject to CLOUD Act",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "Hosting",
    description: "Network infrastructure, CDN, serverless compute, and AI services",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "cf-changelog",
    notes:
      "EU regional placement GA April 2026 for Containers and Durable Objects; DPA available; US parent subject to CLOUD Act",
  },
  {
    id: "daytona",
    name: "Daytona",
    category: "Sandbox",
    description: "Development environment management platform",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "AI",
    description: "AI voice and speech synthesis",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "DPA available; no EU data residency option as of last verification",
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    category: "Search",
    description: "Web scraping and crawling API for AI",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "flyio",
    name: "Fly.io",
    category: "Hosting",
    description: "Global application platform with edge deployment",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available; US-incorporated parent subject to CLOUD Act",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "CI/CD",
    description: "DevOps platform: source control, CI/CD, security scanning",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "GitLab Dedicated EU region available; DPA provided",
  },
  {
    id: "huggingface",
    name: "HuggingFace",
    category: "AI",
    description: "AI model hub and inference API",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU inference endpoints available; US-incorporated parent subject to CLOUD Act",
  },
  {
    id: "inngest",
    name: "Inngest",
    category: "CI/CD",
    description: "Event-driven workflow and background job platform",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    category: "Analytics",
    description: "Product analytics and user behavior tracking",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU residency available; DPA provided",
  },
  {
    id: "neon",
    name: "Neon",
    category: "Database",
    description: "Serverless Postgres with autoscaling and branching",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region (Frankfurt) available; DPA provided",
  },
  {
    id: "notify",
    name: "Notify",
    category: "Communications",
    description: "Push notification and messaging service",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "AI",
    description: "Unified API for multiple LLM providers",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "Routes to underlying providers; residency depends on model selection",
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    category: "Database",
    description: "Serverless MySQL-compatible database",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available; DPA provided",
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "Analytics",
    description: "Open-source product analytics with EU cloud option",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU cloud (Frankfurt) available; self-hostable; open-source codebase",
  },
  {
    id: "privy",
    name: "Privy",
    category: "Auth",
    description: "Embedded wallet and Web3 authentication",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "railway",
    name: "Railway",
    category: "Hosting",
    description: "Application deployment and infrastructure platform",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available; DPA status unconfirmed at last verification",
  },
  {
    id: "render",
    name: "Render",
    category: "Hosting",
    description: "Cloud application hosting platform",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region (Frankfurt) available; DPA provided",
  },
  {
    id: "runloop",
    name: "Runloop",
    category: "Sandbox",
    description: "Secure code execution environment for AI agents",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "Observability",
    description: "Application monitoring and error tracking",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU data residency available; DPA provided",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "Database",
    description: "Open-source Firebase alternative with Postgres",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU regions available (Frankfurt, Stockholm); DPA provided; self-hostable",
  },
  {
    id: "turso",
    name: "Turso",
    category: "Database",
    description: "Edge SQLite database powered by libSQL",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU edge locations available; DPA provided",
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "Communications",
    description: "Cloud communications platform: SMS, voice, email",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available; DPA provided; US parent subject to CLOUD Act",
  },
  {
    id: "upstash",
    name: "Upstash",
    category: "Cache",
    description: "Serverless Redis and Kafka with per-request pricing",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU regions available; DPA provided",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Hosting",
    description: "Frontend cloud platform and edge compute",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available on Enterprise; DPA provided; US parent subject to CLOUD Act",
  },
  {
    id: "workos",
    name: "WorkOS",
    category: "Auth",
    description: "Enterprise SSO, SCIM, and identity management APIs",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU residency available; DPA provided",
  },

  // -------------------------------------------------------------------------
  // Anthropic inference paths (3 separate records — addendum §5.2, decision #14)
  // Verification source: official-docs. Source URLs in notes.
  // us_cloud_act_subject = 1 on Bedrock/Vertex EU paths is intentional:
  // EU regional placement reduces but does not eliminate CLOUD Act reach
  // because the parent (Anthropic, AWS, Google) is US-incorporated.
  // -------------------------------------------------------------------------
  {
    id: "anthropic-direct",
    name: "Anthropic Direct API",
    category: "AI",
    description:
      "Anthropic Claude inference via api.anthropic.com — data processed in the United States",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "official-docs",
    notes: "https://www.anthropic.com/legal/dpa — data processed in US, CLOUD Act applies",
  },
  {
    id: "anthropic-bedrock-eu",
    name: "Anthropic via Bedrock Frankfurt",
    category: "AI",
    description:
      "Anthropic Claude inference via AWS Bedrock eu-central-1 (Frankfurt) — EU data residency with AWS DPA",
    hq_country: "US",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "https://docs.aws.amazon.com/bedrock/latest/userguide/regions.html — eu-central-1 Frankfurt; AWS DPA + SCCs apply, but AWS remains US-parent so CLOUD Act exposure persists",
  },
  {
    id: "anthropic-vertex-eu",
    name: "Anthropic via Vertex AI EU",
    category: "AI",
    description:
      "Anthropic Claude inference via Google Cloud Vertex AI europe-west* endpoints — EU data residency with GCP DPA",
    hq_country: "US",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "https://cloud.google.com/vertex-ai/docs/general/locations — europe-west* endpoints; GCP DPA + SCCs apply, GCP remains US-parent so CLOUD Act exposure persists",
  },
];

// Generates idempotent SQL for seeding sovereignty_db_free.
// INSERT ... ON CONFLICT DO UPDATE per decision #6.
// created_at is never overwritten on update.
export function generateSeedSQL(): string {
  const rows = PROVIDERS.map((p) => {
    const sqlStr = (v: string | null): string =>
      v === null ? "NULL" : `'${v.replace(/'/g, "''")}'`;

    return `INSERT INTO providers (
  id, name, category, description, hq_country,
  data_residency_regions, eu_residency_option, us_cloud_act_subject,
  gdpr_dpa_available, legal_framework, last_verified_at, verification_source, notes
) VALUES (
  ${sqlStr(p.id)}, ${sqlStr(p.name)}, ${sqlStr(p.category)}, ${sqlStr(p.description)}, ${sqlStr(p.hq_country)},
  ${sqlStr(p.data_residency_regions)}, ${p.eu_residency_option}, ${p.us_cloud_act_subject},
  ${p.gdpr_dpa_available}, ${sqlStr(p.legal_framework)}, ${sqlStr(p.last_verified_at)}, ${sqlStr(p.verification_source)}, ${sqlStr(p.notes)}
) ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  hq_country = excluded.hq_country,
  data_residency_regions = excluded.data_residency_regions,
  eu_residency_option = excluded.eu_residency_option,
  us_cloud_act_subject = excluded.us_cloud_act_subject,
  gdpr_dpa_available = excluded.gdpr_dpa_available,
  legal_framework = excluded.legal_framework,
  last_verified_at = excluded.last_verified_at,
  verification_source = excluded.verification_source,
  notes = excluded.notes,
  updated_at = CURRENT_TIMESTAMP;`;
  });

  return rows.join("\n\n");
}

// Runs the seed against a D1Database instance (for wrangler d1 execute or test setup).
// Uses exec() to handle the full SQL without splitting on semicolons — which would
// corrupt statements whose string values contain semicolons (e.g. notes fields).
export async function runSeed(db: D1Database): Promise<void> {
  await db.exec(generateSeedSQL());
}
