// Seed data — source of truth for sovereignty_db_free. D1 is derived from this file.
// All updates must come via PR to this file, never via direct SQL UPDATE (decision #6).
// Seed is idempotent: INSERT ... ON CONFLICT DO UPDATE.
//
// Sources:
//   Stripe Projects providers: verified against projects.dev/providers/ (addendum §5.1)
//   Anthropic records: 3 separate entries per addendum §5.2, verified via official-docs

import type { ProviderRow } from "@/types";

type SeedRow = Omit<ProviderRow, "created_at" | "updated_at">;

export const PROVIDERS: SeedRow[] = [
  // -------------------------------------------------------------------------
  // Stripe Projects providers (32) — verified against projects.dev/providers/
  // -------------------------------------------------------------------------
  {
    id: "agentmail",
    name: "AgentMail",
    category: "Communications",
    description: "Email API for AI agents",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "algolia",
    name: "Algolia",
    category: "Search",
    description: "Search and discovery API",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available; US-parent remains CLOUD Act subject",
  },
  {
    id: "amplitude",
    name: "Amplitude",
    category: "Analytics",
    description: "Product analytics platform",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU data residency available on enterprise plans",
  },
  {
    id: "auth0",
    name: "Auth0/Okta",
    category: "Auth",
    description: "Identity and authentication platform",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU deployment available; Okta US parent subject to CLOUD Act",
  },
  {
    id: "browserbase",
    name: "Browserbase",
    category: "Sandbox",
    description: "Cloud browser infrastructure for AI agents",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "chroma",
    name: "Chroma",
    category: "Database",
    description: "Open-source vector database",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "Self-hosted deployment achieves EU residency; cloud service is US-only",
  },
  {
    id: "clerk",
    name: "Clerk",
    category: "Auth",
    description: "User authentication and management for developers",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU data residency available; US-incorporated parent subject to CLOUD Act",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "Hosting",
    description: "Network infrastructure, CDN, serverless compute, and AI services",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "cf-changelog",
    notes:
      "EU regional placement GA April 2026 for Containers and Durable Objects; DPA available; US parent subject to CLOUD Act",
  },
  {
    id: "daytona",
    name: "Daytona",
    category: "Sandbox",
    description: "Development environment management platform",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "AI",
    description: "AI voice and speech synthesis",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "DPA available; no EU data residency option as of last verification",
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    category: "Search",
    description: "Web scraping and crawling API for AI",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "flyio",
    name: "Fly.io",
    category: "Hosting",
    description: "Global application platform with edge deployment",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available; US-incorporated parent subject to CLOUD Act",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "CI/CD",
    description: "DevOps platform: source control, CI/CD, security scanning",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "GitLab Dedicated EU region available; DPA provided",
  },
  {
    id: "huggingface",
    name: "HuggingFace",
    category: "AI",
    description: "AI model hub and inference API",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU inference endpoints available; US-incorporated parent subject to CLOUD Act",
  },
  {
    id: "inngest",
    name: "Inngest",
    category: "CI/CD",
    description: "Event-driven workflow and background job platform",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    category: "Analytics",
    description: "Product analytics and user behavior tracking",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU residency available; DPA provided",
  },
  {
    id: "neon",
    name: "Neon",
    category: "Database",
    description: "Serverless Postgres with autoscaling and branching",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region (Frankfurt) available; DPA provided",
  },
  {
    id: "notify",
    name: "Notify",
    category: "Communications",
    description: "Push notification and messaging service",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "AI",
    description: "Unified API for multiple LLM providers",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "Routes to underlying providers; residency depends on model selection",
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    category: "Database",
    description: "Serverless MySQL-compatible database",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available; DPA provided",
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "Analytics",
    description: "Open-source product analytics with EU cloud option",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU cloud (Frankfurt) available; self-hostable; open-source codebase",
  },
  {
    id: "privy",
    name: "Privy",
    category: "Auth",
    description: "Embedded wallet and Web3 authentication",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "railway",
    name: "Railway",
    category: "Hosting",
    description: "Application deployment and infrastructure platform",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available; DPA status unconfirmed at last verification",
  },
  {
    id: "render",
    name: "Render",
    category: "Hosting",
    description: "Cloud application hosting platform",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region (Frankfurt) available; DPA provided",
  },
  {
    id: "runloop",
    name: "Runloop",
    category: "Sandbox",
    description: "Secure code execution environment for AI agents",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 0,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: null,
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "Observability",
    description: "Application monitoring and error tracking",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU data residency available; DPA provided",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "Database",
    description: "Open-source Firebase alternative with Postgres",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU regions available (Frankfurt, Stockholm); DPA provided; self-hostable",
  },
  {
    id: "turso",
    name: "Turso",
    category: "Database",
    description: "Edge SQLite database powered by libSQL",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU edge locations available; DPA provided",
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "Communications",
    description: "Cloud communications platform: SMS, voice, email",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available; DPA provided; US parent subject to CLOUD Act",
  },
  {
    id: "upstash",
    name: "Upstash",
    category: "Cache",
    description: "Serverless Redis and Kafka with per-request pricing",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU regions available; DPA provided",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Hosting",
    description: "Frontend cloud platform and edge compute",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU region available on Enterprise; DPA provided; US parent subject to CLOUD Act",
  },
  {
    id: "workos",
    name: "WorkOS",
    category: "Auth",
    description: "Enterprise SSO, SCIM, and identity management APIs",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "stripe-projects",
    notes: "EU residency available; DPA provided",
  },

  // -------------------------------------------------------------------------
  // Anthropic inference paths (3 separate records — addendum §5.2, decision #14)
  // Verification source: official-docs. Source URLs in notes.
  // us_cloud_act_subject = 1 on Bedrock/Vertex EU paths is intentional:
  // EU regional placement reduces but does not eliminate CLOUD Act reach
  // because the parent (Anthropic, AWS, Google) is US-incorporated.
  // -------------------------------------------------------------------------
  {
    id: "anthropic-direct",
    name: "Anthropic Direct API",
    category: "AI",
    description:
      "Anthropic Claude inference via api.anthropic.com — data processed in the United States",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "official-docs",
    notes: "https://www.anthropic.com/legal/dpa — data processed in US, CLOUD Act applies",
  },
  {
    id: "anthropic-bedrock-eu",
    name: "Anthropic via Bedrock Frankfurt",
    category: "AI",
    description:
      "Anthropic Claude inference via AWS Bedrock eu-central-1 (Frankfurt) — EU data residency with AWS DPA",
    hq_country: "US",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "https://docs.aws.amazon.com/bedrock/latest/userguide/regions.html — eu-central-1 Frankfurt; AWS DPA + SCCs apply, but AWS remains US-parent so CLOUD Act exposure persists",
  },
  {
    id: "anthropic-vertex-eu",
    name: "Anthropic via Vertex AI EU",
    category: "AI",
    description:
      "Anthropic Claude inference via Google Cloud Vertex AI europe-west* endpoints — EU data residency with GCP DPA",
    hq_country: "US",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-06T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "https://cloud.google.com/vertex-ai/docs/general/locations — europe-west* endpoints; GCP DPA + SCCs apply, GCP remains US-parent so CLOUD Act exposure persists",
  },

  // -------------------------------------------------------------------------
  // Major platform providers — verified against official documentation
  // us_cloud_act_subject = 1 for all US-incorporated entities.
  // -------------------------------------------------------------------------
  {
    id: "aws",
    name: "AWS",
    category: "Hosting",
    description: "Amazon Web Services — cloud infrastructure, compute, storage, and AI services",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "EU regions: eu-central-1 Frankfurt, eu-west-1 Ireland, eu-west-2 London, eu-west-3 Paris, eu-north-1 Stockholm, eu-south-1 Milan, eu-south-2 Spain; AWS DPA + SCCs; US parent subject to CLOUD Act",
  },
  {
    id: "datadog",
    name: "Datadog",
    category: "Observability",
    description: "Datadog — cloud monitoring, APM, logs, and security platform",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes: "EU site available (app.datadoghq.eu); DPA provided; US parent subject to CLOUD Act",
  },
  {
    id: "github",
    name: "GitHub",
    category: "CI/CD",
    description: "GitHub — source control, Actions CI/CD, and developer collaboration",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes: "Microsoft subsidiary; no EU data residency option; DPA available; CLOUD Act applies",
  },
  {
    id: "google-cloud",
    name: "Google Cloud",
    category: "Hosting",
    description: "Google Cloud Platform — cloud infrastructure, AI, and data services",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "EU regions available (europe-west*); Data Residency restrictions available; Google Cloud DPA + SCCs; US parent subject to CLOUD Act",
  },
  {
    id: "azure",
    name: "Microsoft Azure",
    category: "Hosting",
    description: "Microsoft Azure — cloud computing, AI services, and developer infrastructure",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "EU Data Boundary (2023): EU+EEA data processed and stored in EU; Microsoft DPA + SCCs; US parent subject to CLOUD Act",
  },
  {
    id: "mongodb-atlas",
    name: "MongoDB Atlas",
    category: "Database",
    description: "MongoDB Atlas — managed document database as a service",
    hq_country: "US",
    data_residency_regions: '["US","EU","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "EU regions available (Ireland, Frankfurt, Paris); DPA provided; US parent subject to CLOUD Act",
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "AI",
    description: "OpenAI API — GPT models, embeddings, fine-tuning, and inference",
    hq_country: "US",
    data_residency_regions: '["US"]',
    eu_residency_option: 0,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "US-CLOUD-Act",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "No EU data residency option as of last verification; data processed in US; GDPR DPA available; CLOUD Act applies",
  },
  {
    id: "pinecone",
    name: "Pinecone",
    category: "Database",
    description: "Pinecone — managed vector database for AI and semantic search",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "EU region available (GCP europe-west4 Netherlands); DPA provided; US parent subject to CLOUD Act",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Payments",
    description: "Stripe — online payment processing and financial infrastructure",
    hq_country: "US",
    data_residency_regions: '["US","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 1,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR+SCC",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Stripe Payments Europe Ltd (Dublin IE) processes EU merchant transactions; DPA available; US parent subject to CLOUD Act",
  },

  // -------------------------------------------------------------------------
  // EU-native providers — headquarters in EU/EEA/CH, no US CLOUD Act exposure.
  // us_cloud_act_subject = 0; legal_framework = "GDPR-EU" (EU-incorporated) or
  // "FADP+GDPR" (Swiss-incorporated, adequacy decision applies).
  // These entries are the supply side for suggest_eu_alternatives.
  // -------------------------------------------------------------------------
  {
    id: "adyen",
    name: "Adyen",
    category: "Payments",
    description: "Adyen — Dutch global payment platform for enterprise merchants",
    hq_country: "NL",
    data_residency_regions: '["EU","US","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR-EU",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Adyen N.V., Amsterdam NL; listed on Euronext Amsterdam; no CLOUD Act exposure; own global payment network; DPA available",
  },
  {
    id: "aiven",
    name: "Aiven",
    category: "Database",
    description:
      "Aiven — Finnish managed open-source databases: PostgreSQL, Redis, OpenSearch, Kafka",
    hq_country: "FI",
    data_residency_regions: '["EU","US","APAC"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR-EU",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Aiven Ltd, Helsinki FI; runs on major cloud providers with EU region selection; no CLOUD Act exposure on Aiven layer; DPA available",
  },
  {
    id: "aleph-alpha",
    name: "Aleph Alpha",
    category: "AI",
    description:
      "Aleph Alpha — German sovereign AI platform with on-premises and private cloud options",
    hq_country: "DE",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR-EU",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Aleph Alpha GmbH, Heidelberg DE; on-premises deployment available; no CLOUD Act exposure; DPA available",
  },
  {
    id: "hetzner",
    name: "Hetzner",
    category: "Hosting",
    description:
      "Hetzner — German cloud provider: VPS, dedicated servers, managed Kubernetes, object storage",
    hq_country: "DE",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR-EU",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Hetzner Online GmbH, Gunzenhausen DE; data centers in Germany and Finland; no CLOUD Act exposure; DPA available",
  },
  {
    id: "infomaniak",
    name: "Infomaniak",
    category: "Hosting",
    description: "Infomaniak — Swiss cloud provider: hosting, object storage, email, collaboration",
    hq_country: "CH",
    data_residency_regions: '["CH","EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "FADP+GDPR",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Infomaniak Network SA, Geneva CH; data centers in Switzerland and France; no CLOUD Act exposure; nFADP compliant; EU adequacy decision applies; DPA available",
  },
  {
    id: "mistral-ai",
    name: "Mistral AI",
    category: "AI",
    description: "Mistral AI — European large language models and inference API",
    hq_country: "FR",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR-EU",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Mistral AI SAS, Paris FR; inference served from EU infrastructure; no CLOUD Act exposure; DPA available; models: Mistral Large, Mistral Small, Codestral",
  },
  {
    id: "mollie",
    name: "Mollie",
    category: "Payments",
    description: "Mollie — Dutch payment service provider for European businesses",
    hq_country: "NL",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR-EU",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Mollie B.V., Amsterdam NL; EU-focused operations; no CLOUD Act exposure; licensed by De Nederlandsche Bank; DPA available",
  },
  {
    id: "ovhcloud",
    name: "OVHcloud",
    category: "Hosting",
    description:
      "OVHcloud — French cloud provider: bare metal, VPS, managed Kubernetes, object storage",
    hq_country: "FR",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR-EU",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "OVH SAS, HQ Roubaix FR; data centers across EU (France, Germany, Poland); no CLOUD Act exposure; DPA available",
  },
  {
    id: "plausible",
    name: "Plausible",
    category: "Analytics",
    description: "Plausible — privacy-first web analytics, GDPR compliant by design, no cookies",
    hq_country: "EE",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR-EU",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Plausible Insights OÜ, Tallinn EE; servers on Hetzner Germany; no CLOUD Act exposure; no personal data collection by design; self-hostable; DPA available",
  },
  {
    id: "qdrant",
    name: "Qdrant",
    category: "Database",
    description: "Qdrant — German vector database for AI similarity search and embeddings",
    hq_country: "DE",
    data_residency_regions: '["EU","US"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR-EU",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Qdrant Solutions GmbH, Berlin DE; EU cloud available; open-source and self-hostable; no CLOUD Act exposure; DPA available",
  },
  {
    id: "scaleway",
    name: "Scaleway",
    category: "Hosting",
    description:
      "Scaleway — French cloud provider: compute, object storage, managed databases, serverless",
    hq_country: "FR",
    data_residency_regions: '["EU"]',
    eu_residency_option: 1,
    us_cloud_act_subject: 0,
    gdpr_dpa_available: 1,
    legal_framework: "GDPR-EU",
    last_verified_at: "2026-05-14T00:00:00Z",
    verification_source: "official-docs",
    notes:
      "Online SAS, subsidiary of Iliad Group, Paris FR; data centers in Paris and Amsterdam; no CLOUD Act exposure; DPA available",
  },
];

// Generates idempotent SQL for seeding sovereignty_db_free.
// INSERT ... ON CONFLICT DO UPDATE per decision #6.
// created_at is never overwritten on update.
export function generateSeedSQL(): string {
  const rows = PROVIDERS.map((p) => {
    const sqlStr = (v: string | null): string =>
      v === null ? "NULL" : `'${v.replace(/'/g, "''")}'`;

    return `INSERT INTO providers (
  id, name, category, description, hq_country,
  data_residency_regions, eu_residency_option, us_cloud_act_subject,
  gdpr_dpa_available, legal_framework, last_verified_at, verification_source, notes
) VALUES (
  ${sqlStr(p.id)}, ${sqlStr(p.name)}, ${sqlStr(p.category)}, ${sqlStr(p.description)}, ${sqlStr(p.hq_country)},
  ${sqlStr(p.data_residency_regions)}, ${p.eu_residency_option}, ${p.us_cloud_act_subject},
  ${p.gdpr_dpa_available}, ${sqlStr(p.legal_framework)}, ${sqlStr(p.last_verified_at)}, ${sqlStr(p.verification_source)}, ${sqlStr(p.notes)}
) ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  hq_country = excluded.hq_country,
  data_residency_regions = excluded.data_residency_regions,
  eu_residency_option = excluded.eu_residency_option,
  us_cloud_act_subject = excluded.us_cloud_act_subject,
  gdpr_dpa_available = excluded.gdpr_dpa_available,
  legal_framework = excluded.legal_framework,
  last_verified_at = excluded.last_verified_at,
  verification_source = excluded.verification_source,
  notes = excluded.notes,
  updated_at = CURRENT_TIMESTAMP;`;
  });

  return rows.join("\n\n");
}

// Runs the seed against a D1Database instance (for wrangler d1 execute or test setup).
// Uses exec() to handle the full SQL without splitting on semicolons — which would
// corrupt statements whose string values contain semicolons (e.g. notes fields).
export async function runSeed(db: D1Database): Promise<void> {
  await db.exec(generateSeedSQL());
}
